# This Containerfile produces the environment necessary for
# building CI VM images.  It's intended to be created and used
# by humans or CI, to build targets defined in the Makefile
# at the root of this repository.  It should be built with
# the repository root as the context directory.

ARG CENTOS_RELEASE=stream8
FROM quay.io/centos/centos:${CENTOS_RELEASE}
ARG PACKER_VERSION
MAINTAINER https://github.com/containers/automation_images/image_builder

ENV AI_PATH=/usr/src/automation_images \
    PACKER_INSTALL_DIR=/usr/local/bin \
    PACKER_VERSION=$PACKER_VERSION \
    CONTAINER=1
ADD /image_builder/install* "$AI_PATH/image_builder/"
ADD /image_builder/google-cloud-sdk.repo /etc/yum.repos.d/
ADD /lib.sh "$AI_PATH/"
WORKDIR "$AI_PATH/"
RUN bash ./image_builder/install_packages.sh
ADD ./* "$AI_PATH/"
RUN make install_packer PACKER_INSTALL_DIR="$PACKER_INSTALL_DIR"
