FROM imgts:latest

RUN yum -y --setopt=keepcache=true update

COPY /imgprune/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod 755 /usr/local/bin/entrypoint.sh

# These are only needed by imgts
ENV IMGNAMES="" \
    BUILDID="" \
    REPOREF=""
