---

# Main collection of env. vars to set for all tasks and scripts.
env:
    # Name of the ultimate destination branch for this CI run, PR or post-merge.
    DEST_BRANCH: "main"
    # Shell used to execute all script commands
    CIRRUS_SHELL: "/bin/bash"
    # No need to go crazy, but grab enough to cover most PRs
    CIRRUS_CLONE_DEPTH: 50
    # Version of packer to use when building images
    PACKER_VERSION: &PACKER_VERSION "1.8.3"
    #IMG_SFX = <See IMG_SFX file and .cirrus.star script>
    #IMPORT_IMG_SFX = <See IMPORT_IMG_SFX file and .cirrus.star script>


gcp_credentials: ENCRYPTED[823fdbc2fee3c27fa054ba1e9cfca084829b5e71572f1703a28e0746b1a924ee5860193f931adce197d40bf89e7027fe]

# Build and push podman/buildah/skopeo container images daily
quay_io_images_task:
    name: "Periodicly build and push $FLAVOR_NAME quay.io $REPO_NAME container images"
    alias: quay_io_images
    # Multi-arch builds w/ emulation are especially 'slow'
    timeout_in: 120m
    gce_instance:
        image_project: "libpod-218412"
        # Hack: Use the 'latest' CI VM image instead of a specific 'image_name'.
        # Not all PRs produce VM images but may change build-push scripts and
        # alter IMG_SFX.  This accounts for both situations in a mostly-okay way.
        image_family: 'build-push-cache'
        zone: "us-central1-a"
        disk: 200
        # More muscle to emulate multi-arch
        type: "n2-standard-4"
    env:
        REPO_PFX: https://github.com/containers
        CONTAINERS_USERNAME: ENCRYPTED[c1ffcce3982029bc26daf266fda73f80f49485974b5f1d94d86d5b10e3e6ca55f4089d4559833391651cfff3edfa0897]
        CONTAINERS_PASSWORD: ENCRYPTED[4b1ce64d16782ebaafe845376fdc7af64ee4afed6fe64750c8bc77c795d01cd0339ada2520f1a1cd43b11ad6677663f3]
        FLAVOR_NAME: upstream
        A_DEBUG: 1
        REPO_NAME: skopeo
        CTX_SUB: contrib/${REPO_NAME}image/${FLAVOR_NAME}
        SKOPEO_USERNAME: ENCRYPTED[8ef796801eef6fd4f38ee5d4693353e3e1b471c251cef77d4f0547e726af3550812f314f0376220177f49f08a1e5a695]
        SKOPEO_PASSWORD: ENCRYPTED[0a08c914b434693fe0c6afb4cf3f1c905aea04846eb860041c7660fd891cf097b05eac87002f75ad23af9a775e8b0d47]

    # Always use the latest/greatest scripts from main to allow quick adjustments
    # when needed - i.e. not requiring completely fresh VM images to be built.
    script: |
        bash ./build-push/.install.sh
        source /etc/automation_environment
        containers_build_push.sh ${REPO_PFX}/${REPO_NAME}.git $CTX_SUB $FLAVOR_NAME
