FROM imgts:latest

COPY /orphanvms/entrypoint.sh /orphanvms/_gce /orphanvms/_ec2 /usr/local/bin/
RUN chmod 755 /usr/local/bin/entrypoint.sh

# Clear unneeded requirements, add GCPPROJECTS and AWSINI as required
ENV GCPPROJECT="" \
    IMGNAMES="" \
    BUILDID="" \
    REPOREF="" \
    GCPPROJECTS="__unknown__" \
    AWSINI="__unknown__"
