ARG BASE_NAME=registry.fedoraproject.org/fedora-minimal
ARG BASE_TAG=latest
FROM ${BASE_NAME}:${BASE_TAG} as updated_base

RUN microdnf update -y && \
    microdnf clean all

ENV _RUNTIME_DEPS="bash python3"
ENV _BUILD_DEPS="coreutils curl git python3 python3-pip python3-virtualenv python3-devel gcc g++"


FROM updated_base as builder

RUN microdnf install -y ${_RUNTIME_DEPS} ${_BUILD_DEPS} && \
    export INSTALL_PREFIX=/usr/share && \
    curl -sL \
        https://raw.githubusercontent.com/containers/automation/main/bin/install_automation.sh | \
        bash -s latest bench_stuff


FROM updated_base as final

ADD bench_stuff/entrypoint.sh /usr/local/bin/

RUN microdnf install -y ${_RUNTIME_DEPS} && \
    microdnf clean all && \
    chmod +x /usr/local/bin/entrypoint.sh

COPY --from=builder /usr/share/automation /usr/share/automation
COPY --from=builder /etc/automation_environment /etc/automation_environment

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
