FROM quay.io/centos/centos:stream8

# Only needed for installing build-time dependencies
COPY /imgts/google-cloud-sdk.repo /etc/yum.repos.d/google-cloud-sdk.repo
RUN echo 'keepcache=true' >> /etc/dnf/dnf.conf && \
    dnf -y update && \
    dnf -y install epel-release python3 && \
    dnf -y --exclude=google-cloud-sdk-366.0.0-1 \
        install google-cloud-sdk

# These all represent required variables which must be set by caller
ENV GCPJSON="__unknown__" \
    GCPNAME="__unknown__" \
    GCPPROJECT="__unknown__" \
    IMGNAMES="__unknown__" \
    BUILDID="__unknown__" \
    REPOREF="__unknown__"

COPY ["/imgts/entrypoint.sh", "/imgts/lib_entrypoint.sh", "/usr/local/bin/"]
RUN chmod 755 /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
