FROM centos:8

# Only needed for installing build-time dependencies
COPY /imgts/google-cloud-sdk.repo /etc/yum.repos.d/google-cloud-sdk.repo
RUN yum -y update && \
    yum -y install epel-release && \
    yum -y install google-cloud-sdk && \
    yum clean all

# These all represent required variables which must be set by caller
ENV GCPJSON="__unknown__" \
    GCPNAME="__unknown__" \
    GCPPROJECT="__unknown__" \
    IMGNAMES="__unknown__" \
    BUILDID="__unknown__" \
    REPOREF="__unknown__"

COPY ["/imgts/entrypoint.sh", "/imgts/lib_entrypoint.sh", "/usr/local/bin/"]
RUN chmod 755 /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
