ARG CENTOS_STREAM_RELEASE=8
FROM quay.io/centos/centos:stream${CENTOS_STREAM_RELEASE}

ARG dnfycache="dnf -y --setopt=keepcache=true"

# Only needed for installing build-time dependencies
COPY /imgts/google-cloud-sdk.repo /etc/yum.repos.d/google-cloud-sdk.repo
RUN ${dnfycache} update && \
    ${dnfycache} install epel-release && \
    ${dnfycache} install python3 jq && \
    ${dnfycache} --exclude=google-cloud-sdk-366.0.0-1 \
        install google-cloud-sdk

# https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
ARG AWSURL="https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
RUN ${dnfycache} install unzip glibc groff-base less && \
    cd /tmp && \
    curl --fail --location -O "${AWSURL}" && \
    unzip awscli*.zip && \
    ./aws/install -i /usr/local/share/aws-cli -b /usr/local/bin && \
    rm -rf awscli*.zip ./aws

# Env. vars set to "__unknown__" are required to be set by the caller;
# Except, an AWSINI value is required if EC2IMGNAMES is non-empty.
ENV GCPJSON="__unknown__" \
    GCPNAME="__unknown__" \
    GCPPROJECT="__unknown__" \
    IMGNAMES="__unknown__" \
    BUILDID="__unknown__" \
    REPOREF="__unknown__" \
    EC2IMGNAMES="" \
    AWSINI=""

COPY ["/imgts/entrypoint.sh", "/imgts/lib_entrypoint.sh", "/usr/local/bin/"]
RUN chmod 755 /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
