# This dockerfile defines the environment for Cirrus-CI when
# running automated checks and tests. It may also be used
# for development/debugging or manually building most
# Makefile targets.

ARG FEDORA_RELEASE=32
FROM registry.fedoraproject.org/fedora:${FEDORA_RELEASE}
MAINTAINER https://github.com/containers/automation_images/ci

ENV CIRRUS_WORKING_DIR=/tmp/automation_images \
    PACKER_INSTALL_DIR=/usr/local/bin \
    VERSION=1
ADD ./ci/install* "$CIRRUS_WORKING_DIR/ci/"
WORKDIR "$CIRRUS_WORKING_DIR/"
RUN bash ./ci/install_packages.sh
# Overwrite prior add, allows build cache to skip install_packages.sh when possible
ADD ./* "$CIRRUS_WORKING_DIR/"
RUN make install_packer PACKER_INSTALL_DIR="$PACKER_INSTALL_DIR"
