ARG BASE_NAME=registry.fedoraproject.org/fedora-minimal
# FIXME FIXME FIXME! 2023-11-16: revert "38" to "latest"
# ...38 is because as of this moment, latest is 39, which
# has python-3.12, which causes something to barf:
#         aiohttp/_websocket.c:3744:45: error: ‘PyLongObject’ {aka ‘struct _longobject’} has no member named ‘ob_digit’
# Possible cause: https://github.com/cython/cython/issues/5238
ARG BASE_TAG=38
FROM ${BASE_NAME}:${BASE_TAG} as updated_base

RUN microdnf upgrade -y && \
    microdnf clean all

ENV _RUNTIME_DEPS="bash python3"
ENV _BUILD_DEPS="coreutils curl git python3 python3-pip python3-virtualenv python3-devel gcc g++"


FROM updated_base as builder

RUN microdnf install -y ${_RUNTIME_DEPS} ${_BUILD_DEPS} && \
    export INSTALL_PREFIX=/usr/share && \
    curl -sL \
        https://raw.githubusercontent.com/containers/automation/main/bin/install_automation.sh | \
        bash -s latest cirrus-ci_artifacts


FROM updated_base as final

RUN microdnf install -y ${_RUNTIME_DEPS} && \
    microdnf clean all

COPY --from=builder /usr/share/automation /usr/share/automation
COPY --from=builder /etc/automation_environment /etc/automation_environment

# Env. is used by test.sh script.
ENV CCIABIN=/usr/share/automation/bin/cirrus-ci_artifacts
ENTRYPOINT ["/usr/share/automation/bin/cirrus-ci_artifacts"]
