ARG BASE_NAME=registry.fedoraproject.org/fedora-minimal
ARG BASE_TAG=latest
FROM ${BASE_NAME}:${BASE_TAG} as updated_base

RUN microdnf update -y && \
    microdnf clean all && \
    rm -rf /var/cache/dnf

ENV _RUNTIME_DEPS="bash python3"
ENV _BUILD_DEPS="coreutils curl git python3 python3-pip python3-virtualenv python3-devel gcc g++"


FROM updated_base as builder

RUN microdnf install -y ${_RUNTIME_DEPS} ${_BUILD_DEPS} && \
    export INSTALL_PREFIX=/usr/share && \
    curl -sL \
        https://raw.githubusercontent.com/containers/automation/master/bin/install_automation.sh | \
        bash -s latest cirrus-ci_artifacts


FROM updated_base as final

RUN microdnf install -y ${_BUILD_DEPS} && \
    microdnf clean all && \
    rm -rf /var/cache/dnf

COPY --from=builder /usr/share/automation /usr/share/automation
COPY --from=builder /etc/automation_environment /etc/automation_environment

ENTRYPOINT ["/usr/share/automation/bin/cirrus-ci_artifacts"]
VOLUME ["/data"]
WORKDIR /data
