# This produces fource container images intended to be utilized
# by podman automation for building and testing podman inside a
# container environment.  All four must be built using the
# top-level Makefile.

# N/B: The BASE_NAME and BASE_TAG build-vars are required.  Supported
#      values for Fedora and Debian, are specified in the *_release
#      files within this dir.

ARG BASE_NAME=
ARG BASE_TAG=
FROM ${BASE_NAME}:${BASE_TAG}

ARG PACKER_BUILD_NAME=
ENV AI_PATH=/usr/src/automation_images \
    CONTAINER=1

# Only add needed files to avoid invalidating build cache
ADD /lib.sh "$AI_PATH/"
ADD /podman/* "$AI_PATH/podman/"
ADD /base_images/* "$AI_PATH/base_images/"
ADD /cache_images/* "$AI_PATH/cache_images/"
ADD /systemd_banish.sh "$AI_PATH/"
WORKDIR "$AI_PATH"
RUN bash ./podman/setup.sh

#### For runtime use...

# The podman source to be tested must be volume-mounted in, and its
# directory location reflected in or by overriding the $GOSRC env.
# var. value at runtime.

ENV GOPATH=/var/tmp/go
ENV GOSRC=$GOPATH/src/github.com/containers/podman
RUN mkdir -p "$GOSRC"
WORKDIR "$GOSRC"
